#pragma once

static const char index_html[] =
"<!DOCTYPE html><html><head><meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Wrmhole</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:monospace;background:#0a0a0a;color:#0f0;padding:15px}"
"h1{text-align:center;margin-bottom:15px;text-shadow:0 0 8px #0f0}"
".c{max-width:700px;margin:0 auto}"
".card{background:#111;border:1px solid #0f0;border-radius:6px;padding:15px;margin-bottom:15px}"
".card h2{border-bottom:1px solid #0f0;padding-bottom:8px;margin-bottom:10px;font-size:14px}"
"button{background:#0f0;color:#000;border:none;padding:8px 16px;border-radius:4px;cursor:pointer;font-weight:bold;margin:4px;font-family:monospace}"
"button:hover{background:#0c0}"
"button.d{background:#f44}"
"button.d:hover{background:#c00}"
"button.sm{padding:3px 8px;font-size:11px;margin:1px}"
"button.sm.add{background:#0f0}"
"button.sm.rm{background:#f44}"
"select,input{background:#000;color:#0f0;border:1px solid #0f0;padding:6px 10px;border-radius:4px;margin:4px;font-family:monospace}"
"table{width:100%;border-collapse:collapse;margin-top:8px;font-size:12px}"
"th,td{padding:6px;text-align:left;border-bottom:1px solid #333}"
"th{background:#1a1a1a}"
"tr:hover{background:#1a1a1a}"
"#log{background:#000;padding:8px;border-radius:4px;height:150px;overflow-y:auto;font-size:11px}"
".st{padding:8px;margin:8px 0;border-radius:4px;background:#1a1a1a;border-left:3px solid #0f0}"
".st.on{border-left-color:#f44;background:#200}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}"
".pulse{animation:pulse 1s infinite}"
"</style></head><body><div class='c'>"
"<h1>Wrmhole</h1>"
"<div class='card'><h2 id='sht'>STATUS</h2><div class='st' id='st'>Loading...</div>"
"<button onclick='refresh()'>Refresh</button>"
"<button id='scanbtn' onclick='scan()'>Scan</button></div>"
"<div class='card'><h2>NETWORKS</h2><div id='nets'>Click Scan</div></div>"
"<div class='card'><h2>CLIENTS</h2><div id='cls'>Click Scan</div></div>"
"<div class='card'><h2>MONITOR</h2><div id='mon'>Auto-updates every 2s</div></div>"
"<div class='card'><h2>WHITELIST</h2><div id='wl'>Empty</div>"
"<div><input type='text' id='wlmac' placeholder='AA:BB:CC:DD:EE:FF' style='width:160px'>"
"<button onclick='wladd()'>Add</button></div></div>"
"<div class='card'><h2>BLE SPAM</h2>"
"<div><select id='ble_type'>"
"<option value='apple'>Apple (AirPods/AppleTV)</option>"
"<option value='samsung'>Samsung (Galaxy Watch)</option>"
"<option value='google'>Google (Fast Pair)</option>"
"<option value='all'>All (rotate)</option></select></div>"
"<div>Packets sent: <span id='ble_count'>0</span></div>"
"<br><button class='d' onclick='ble_start()'>START BLE SPAM</button>"
"<button onclick='ble_stop()'>STOP</button></div>"
"<div class='card'><h2>DEAUTH ATTACK</h2>"
"<div><select id='tgt' onchange='document.getElementById(\"csl\").style.display=this.value==\"client\"?\"inline-block\":\"none\";document.getElementById(\"manmac\").style.display=this.value==\"manual\"?\"inline-block\":\"none\"'>"
"<option value='all'>All (broadcast)</option>"
"<option value='client'>Specific client (from scan)</option>"
"<option value='manual'>Manual MAC</option></select>"
"<select id='csl' style='display:none'><option value=''>Select client</option></select>"
"<input type='text' id='manmac' placeholder='AA:BB:CC:DD:EE:FF' style='width:160px;display:none'></div>"
"<div><select id='rsn'><option value='1'>1-Unspecified</option>"
"<option value='3'>3-Deauth leaving</option>"
"<option value='4' selected>4-Inactivity</option>"
"<option value='7'>7-Class3 frame</option></select></div>"
"<div><input type='number' id='brst' value='10' min='1' max='100' style='width:60px'> packets/burst"
"<br><input type='number' id='intrv' value='0' min='0' max='10000' style='width:60px'> ms interval (0=continuous)</div>"
"<br><button class='d' onclick='start()'>START</button>"
"<button onclick='stop()'>STOP</button></div>"
"<div class='card'><h2>WIFI CONFIG</h2>"
"<div>Current SSID: <b id='cur_ssid'>-</b> | Connected: <b id='cur_conn'>-</b></div>"
"<div><input type='text' id='wssid' placeholder='SSID' style='width:160px'>"
"<input type='text' id='wpass' placeholder='Password' style='width:160px'>"
"<button onclick='wifiset()'>Save</button></div>"
"<div><button onclick='wifireset()'>Reset to defaults</button>"
"<button onclick='if(confirm(\"Reboot?\"))fetch(\"/api/reboot\")'>Reboot</button></div></div>"
"<div class='card'><h2>LOG</h2><div id='log'></div></div>"
"</div><script>"
"var _on=false;"
"function L(m){var l=document.getElementById('log');"
"l.innerHTML+='<div>['+new Date().toLocaleTimeString()+'] '+m+'</div>';"
"l.scrollTop=l.scrollHeight}"
"function upSt(d){"
"var st=document.getElementById('st');"
"var sh=document.getElementById('sht');"
"_on=(d.mode==='DEAUTH' || d.mode==='BLE_SPAM');"
"var c='WiFi: '+(d.wifi?'OK '+d.ssid:'AP mode')+'<br>IP: '+d.ip+'<br>Target: '+d.target_ssid+' ('+d.target_bssid+') ch:'+d.target_channel+'<br>Mode: <b>'+d.mode+'</b><br>Packets: '+d.deauth_count+'<br>Clients: '+d.client_count;"
"if(d.ble_spam){c+='<br>BLE Spam: <b>RUNNING</b> ('+d.ble_spam_count+' packets)';}"
"st.innerHTML=c;"
"st.className=_on?'st on pulse':'st';"
"sh.innerHTML=_on?'<span style=color:#f44>&#9679;</span> ATTACK RUNNING':'STATUS';"
"document.getElementById('ble_count').textContent=d.ble_spam_count||0;"
"document.getElementById('cur_ssid').textContent=d.ssid||'-';"
"document.getElementById('cur_conn').textContent=d.wifi?'Yes':'No';"
"if(d.clients_detail&&d.clients_detail.length>0){"
"var m='<table><tr><th>MAC</th><th>Vendor</th><th>RSSI</th><th>Ch</th></tr>';"
"d.clients_detail.forEach(function(c){"
"var color=c.rssi>-50?'#0f0':c.rssi>-70?'#ff0':'#f44';"
"m+='<tr><td>'+c.mac+'</td><td>'+c.vendor+'</td><td style=\"color:'+color+'\">'+c.rssi+' dBm</td><td>'+c.channel+'</td></tr>';"
"});m+='</table>';document.getElementById('mon').innerHTML=m;}}"
"function refresh(){fetch('/api/status').then(function(r){return r.json()}).then(function(d){upSt(d)}).catch(function(e){L('Error: '+e)})}"
"function scan(){var b=document.getElementById('scanbtn');b.disabled=true;b.textContent='Scanning...';b.style.background='#f44';"
"L('Scanning...');fetch('/api/scan').then(function(r){return r.json()}).then(function(d){"
"var h='<table><tr><th>SSID</th><th>BSSID</th><th>Ch</th><th>RSSI</th></tr>';"
"d.networks.forEach(function(n){h+='<tr><td>'+n.ssid+'</td><td>'+n.bssid+'</td><td>'+n.channel+'</td><td>'+n.rssi+'</td></tr>'});h+='</table>';"
"document.getElementById('nets').innerHTML=h;"
"h='<table><tr><th>MAC</th><th>Vendor</th><th>RSSI</th><th>Ch</th><th>WL</th></tr>';"
"d.clients.forEach(function(c){"
"h+='<tr><td>'+c.mac+'</td><td>'+c.vendor+'</td><td>'+c.rssi+'</td><td>'+c.channel+'</td><td>';"
"h+=c.whitelisted"
"?'<button class=\"sm rm\" onclick=\"wlrm(\\''+c.mac+'\\')\">- WL</button>'"
":'<button class=\"sm add\" onclick=\"wladdm(\\''+c.mac+'\\')\">+ WL</button>';"
"h+='</td></tr>'});h+='</table>';"
"document.getElementById('cls').innerHTML=h;"
"var s=document.getElementById('csl');s.innerHTML='<option value=\"\">Select</option>';"
"d.clients.forEach(function(c){s.innerHTML+='<option value=\"'+c.mac+'\">'+c.mac+' ('+c.vendor+')</option>'});"
"L('Found: '+d.networks.length+' networks, '+d.clients.length+' clients');"
"b.disabled=false;b.textContent='Scan';b.style.background='';})}"
"function wladd(){var m=document.getElementById('wlmac').value;if(!m){return}"
"fetch('/api/whitelist/add?mac='+m).then(function(r){return r.json()}).then(function(d){L('Whitelist: '+d.count);wlrefresh()})}"
"function wladdm(m){"
"fetch('/api/whitelist/add?mac='+m).then(function(r){return r.json()}).then(function(d){L('Added '+m);wlrefresh()})}"
"function wlrm(m){fetch('/api/whitelist/remove?mac='+m).then(function(r){return r.json()}).then(function(d){L('Removed '+m);wlrefresh()})}"
"function wlrefresh(){fetch('/api/whitelist').then(function(r){return r.json()}).then(function(d){"
"var h='';if(d.count==0){h='Empty'}else{"
"d.whitelist.forEach(function(m){h+='<div>'+m+' <button class=\"sm rm\" onclick=\"wlrm(\\''+m+'\\')\">remove</button></div>'});}"
"document.getElementById('wl').innerHTML=h;})}"
"function start(){var t=document.getElementById('tgt').value;"
"var r=document.getElementById('rsn').value;"
"var b=document.getElementById('brst').value;"
"var iv=document.getElementById('intrv').value;"
"var u='/api/deauth?reason='+r+'&burst='+b+'&interval='+iv;"
"if(t=='client'){var c=document.getElementById('csl').value;"
"if(!c){L('Select client!');return}u+='&client='+c}"
"else if(t=='manual'){var m=document.getElementById('manmac').value;"
"if(!m){L('Enter MAC!');return}u+='&client='+m}"
"L('Attack: '+(t=='all'?'broadcast':(t=='manual'?m:c)));"
"fetch(u).then(function(r){return r.json()}).then(function(d){L(d.status);refresh()})"
"}"
"function stop(){fetch('/api/stop').then(function(r){return r.json()}).then(function(d){L(d.status);refresh()})"
"}"
"function ble_start(){var t=document.getElementById('ble_type').value;"
"L('BLE Spam: '+t);"
"fetch('/api/ble/spam/start?type='+t).then(function(r){return r.json()}).then(function(d){L(d.status);refresh()})"
"}"
"function ble_stop(){fetch('/api/ble/spam/stop').then(function(r){return r.json()}).then(function(d){L(d.status);refresh()})"
"}"
"function wifiset(){var s=document.getElementById('wssid').value;var p=document.getElementById('wpass').value;"
"if(!s){L('Enter SSID!');return}"
"fetch('/api/wifi/set?ssid='+encodeURIComponent(s)+'&pass='+encodeURIComponent(p))"
".then(function(r){return r.json()}).then(function(d){L(d.status);refresh()})}"
"function wifireset(){if(!confirm('Reset WiFi to defaults?'))return;"
"fetch('/api/wifi/reset').then(function(r){return r.json()}).then(function(d){L(d.status);refresh()})}"
"refresh();setInterval(refresh,2000);wlrefresh();"
"</script></body></html>";
